### ISSUE TITLE
Compatibility with OpenStack Keystone auth v3

### ISSUE THREAD

**Issue by lukastopiarz** [Lirt/velero-plugin-swift#11]
Hello,
Is this plugin compatible with OpenStack Keystone auth v3? 
Gophercloud library seems to be ready for v3 (http://gophercloud.io/docs/identity/v3/)

Velero backup pod keeps crashing with error message:

> time="2020-11-05T07:28:49Z" level=info msg="ObjectStore.Init called" cmd=/plugins/velero-plugin-swift logSource="/go/src/github.com/Lirt/velero-plugin-swift/src/object_store.go:61" pluginName=velero-plugin-swift
> An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = Failed to authenticate against Swift: You must provide exactly one of DomainID or DomainName to authenticate by Username

For testing purposes, I set manually all the OS variables (Taken from OpenStack RC3) file in the velero deployment like:
```
    spec:
      containers:
      - args:
        - server
        - --features=
        command:
        - /velero
        env:
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LD_LIBRARY_PATH
          value: /plugins
        - name: OS_AUTH_URL
          value: https://xxx.zzz.com:5000/v3  << Auth v3
        - name: OS_PASSWORD
          value: passwordxxx
        - name: OS_REGION_NAME
          value: regionxxx
        - name: OS_USERNAME
          value: usernamexxx
        - name: OS_PROJECT_DOMAIN_ID
          value: domainidxxx
        - name: OS_USER_DOMAIN_ID
          value: domainidxxx
```

Do you need any additional info?

Anyway thanks for your work! I would be very happy if I can use it in our environment.
